---
services:
  web:
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    networks:
      - transfer
    ports:
      - '53:53/udp'
      - '53:53/tcp'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.adguard.rule: 'Host(`adguard.example.com`)'
      traefik.http.routers.adguard.entrypoints: 'web'
      traefik.http.services.adguard.loadbalancer.server.port: '3000'

networks:
  transfer:
    external: true

volumes:
  work:
  conf:
